language: ruby
sudo: required
services:
  - docker
before_install:
  - sudo apt-get update && sudo apt-get install docker-engine && docker -v
  - docker pull exorath/mapservice && docker run -d -p 0.0.0.0:8080:8080 -e PORT=8080 -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_KEY -e BUCKET_NAME exorath/mapservice
script:
  - version=${TRAVIS_TAG-latest} ;
    if [ "$TRAVIS_TAG" == "" ]; then
    version=latest;
    fi ;
    docker build --network host --build-arg GITHUB_OAUTH=${GITHUB_OAUTH} --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_KEY=${AWS_SECRET_KEY} --build-arg EULA=${EULA} --build-arg AWS_REGION=${AWS_REGION}  -t build-image . ;
    docker create --name=build-container build-image cat;
    docker cp build-container:/usr/src/mcserver/. ./mcserver && docker cp build-container:/usr/bin/startserver ./mcserver;
    docker build -f Dockerfile.release -t exorath/server-cakewars:${version} .
after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    echo "version $TRAVIS_TAG" ;
    docker push "exorath/server-cakewars:$TRAVIS_TAG" ;
    fi 
