FROM openjdk:8-jdk

COPY ./mcserver/. /usr/src/mcserver/
COPY ./mcserver/startserver /usr/bin/
WORKDIR /usr/src/mcserver

RUN apt-get update && apt-get install -y tmux && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["startserver"]
